//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.buff
{

public sealed partial class BuffItems
{
    private readonly Dictionary<int, buff.BuffItem> _dataMap;
    private readonly List<buff.BuffItem> _dataList;
    
    public BuffItems(JSONNode _json)
    {
        _dataMap = new Dictionary<int, buff.BuffItem>();
        _dataList = new List<buff.BuffItem>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = buff.BuffItem.DeserializeBuffItem(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, buff.BuffItem> DataMap => _dataMap;
    public List<buff.BuffItem> DataList => _dataList;

    public buff.BuffItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public buff.BuffItem Get(int key) => _dataMap[key];
    public buff.BuffItem this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}