//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.skill
{
    public enum SkillType
    {
        /// <summary>
        /// 主动技能
        /// </summary>
        Erupt = 0,
        /// <summary>
        /// 出场技能
        /// </summary>
        Coming = 1,
        /// <summary>
        /// 被动技能
        /// </summary>
        Passive = 2,
    }
}
