//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// 标记元素
    /// </summary>
    public enum Element
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 水
        /// </summary>
        Hydro = 1,
        /// <summary>
        /// 火
        /// </summary>
        Pyro = 2,
        /// <summary>
        /// 冰
        /// </summary>
        Cryo = 3,
        /// <summary>
        /// 雷
        /// </summary>
        Electro = 4,
        /// <summary>
        /// 岩
        /// </summary>
        Geo = 5,
        /// <summary>
        /// 风
        /// </summary>
        Anemo = 6,
    }
}
