//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.common
{
    /// <summary>
    /// 标记回合时间
    /// </summary>
    public enum RoundTime
    {
        /// <summary>
        /// 默认
        /// </summary>
        Default = 0,
        /// <summary>
        /// 回合开始
        /// </summary>
        OnRoundStart = 1,
        /// <summary>
        /// 回合中
        /// </summary>
        OnRound = 2,
        /// <summary>
        /// 回合结束
        /// </summary>
        OnRoundEnd = 3,
    }
}
