//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.effect
{
    /// <summary>
    /// Buff重载标识
    /// </summary>
    [System.Flags]
    public enum BuffPropertiesOverrideable
    {
        /// <summary>
        /// 不可重载
        /// </summary>
        None = 0,
        /// <summary>
        /// 重载层数
        /// </summary>
        Stories = 1,
        /// <summary>
        /// 重载持续
        /// </summary>
        LifeCycles = 2,
        /// <summary>
        /// 均可重载
        /// </summary>
        All = Stories|LifeCycles,
    }
}
