//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.effect
{
    /// <summary>
    /// 标记Effect类型
    /// </summary>
    public enum EffectType
    {
        /// <summary>
        /// 伤害类
        /// </summary>
        Damage = 0,
        /// <summary>
        /// 挂Buff类
        /// </summary>
        AddBuff = 1,
        /// <summary>
        /// 恢复类
        /// </summary>
        Cure = 2,
        /// <summary>
        /// 抽卡类
        /// </summary>
        Draw = 3,
    }
}
