//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.effect
{
    public enum TargetArea
    {
        /// <summary>
        /// 缺省
        /// </summary>
        None = 0,
        /// <summary>
        /// 单体目标
        /// </summary>
        Mono = 1,
        /// <summary>
        /// 周围目标
        /// </summary>
        AOE = 2,
        /// <summary>
        /// 所有目标
        /// </summary>
        All = 3,
    }
}
