//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.card
{
    public enum CardType
    {
        /// <summary>
        /// 角色
        /// </summary>
        Chara = 0,
        /// <summary>
        /// 怪物
        /// </summary>
        Monster = 1,
        /// <summary>
        /// 大怪
        /// </summary>
        Boss = 2,
    }
}
