//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.level
{

public sealed partial class CardLibrary :  Bright.Config.BeanBase 
{
    public CardLibrary(JSONNode _json) 
    {
        { if(!_json["Id"].IsNumber) { throw new SerializationException(); }  Id = _json["Id"]; }
        { if(!_json["Owner"].IsNumber) { throw new SerializationException(); }  Owner = _json["Owner"]; }
        { if(!_json["Desc"].IsString) { throw new SerializationException(); }  Desc = _json["Desc"]; }
        { var _json1 = _json["CharaList"]; if(!_json1.IsArray) { throw new SerializationException(); } CharaList = new System.Collections.Generic.List<int>(_json1.Count); foreach(JSONNode __e in _json1.Children) { int __v;  { if(!__e.IsNumber) { throw new SerializationException(); }  __v = __e; }  CharaList.Add(__v); }   }
        { var _json1 = _json["CardList"]; if(!_json1.IsArray) { throw new SerializationException(); } CardList = new System.Collections.Generic.List<int>(_json1.Count); foreach(JSONNode __e in _json1.Children) { int __v;  { if(!__e.IsNumber) { throw new SerializationException(); }  __v = __e; }  CardList.Add(__v); }   }
        PostInit();
    }

    public CardLibrary(int Id, int Owner, string Desc, System.Collections.Generic.List<int> CharaList, System.Collections.Generic.List<int> CardList ) 
    {
        this.Id = Id;
        this.Owner = Owner;
        this.Desc = Desc;
        this.CharaList = CharaList;
        this.CardList = CardList;
        PostInit();
    }

    public static CardLibrary DeserializeCardLibrary(JSONNode _json)
    {
        return new level.CardLibrary(_json);
    }

    /// <summary>
    /// 卡组id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 持有者id
    /// </summary>
    public int Owner { get; private set; }
    /// <summary>
    /// 卡组描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// Chara01
    /// </summary>
    public System.Collections.Generic.List<int> CharaList { get; private set; }
    /// <summary>
    /// Card01
    /// </summary>
    public System.Collections.Generic.List<int> CardList { get; private set; }

    public const int __ID__ = 508199937;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Owner:" + Owner + ","
        + "Desc:" + Desc + ","
        + "CharaList:" + Bright.Common.StringUtil.CollectionToString(CharaList) + ","
        + "CardList:" + Bright.Common.StringUtil.CollectionToString(CardList) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
