//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.level
{

public sealed partial class EventDialogItems
{
    private readonly Dictionary<int, level.EventDialogItem> _dataMap;
    private readonly List<level.EventDialogItem> _dataList;
    
    public EventDialogItems(JSONNode _json)
    {
        _dataMap = new Dictionary<int, level.EventDialogItem>();
        _dataList = new List<level.EventDialogItem>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = level.EventDialogItem.DeserializeEventDialogItem(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, level.EventDialogItem> DataMap => _dataMap;
    public List<level.EventDialogItem> DataList => _dataList;

    public level.EventDialogItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.EventDialogItem Get(int key) => _dataMap[key];
    public level.EventDialogItem this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}