//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.level
{

public sealed partial class LevelBattleItem :  Bright.Config.BeanBase 
{
    public LevelBattleItem(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["BattleStagePath"].IsString) { throw new SerializationException(); }  BattleStagePath = _json["BattleStagePath"]; }
        { if(!_json["BossId"].IsNumber) { throw new SerializationException(); }  BossId = _json["BossId"]; }
        { if(!_json["EnemyCardDeck"].IsNumber) { throw new SerializationException(); }  EnemyCardDeck = _json["EnemyCardDeck"]; }
        { if(!_json["EnemyAI"].IsNumber) { throw new SerializationException(); }  EnemyAI = _json["EnemyAI"]; }
        PostInit();
    }

    public LevelBattleItem(int id, string BattleStagePath, int BossId, int EnemyCardDeck, int EnemyAI ) 
    {
        this.Id = id;
        this.BattleStagePath = BattleStagePath;
        this.BossId = BossId;
        this.EnemyCardDeck = EnemyCardDeck;
        this.EnemyAI = EnemyAI;
        PostInit();
    }

    public static LevelBattleItem DeserializeLevelBattleItem(JSONNode _json)
    {
        return new level.LevelBattleItem(_json);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 战斗场景
    /// </summary>
    public string BattleStagePath { get; private set; }
    /// <summary>
    /// Boss配置
    /// </summary>
    public int BossId { get; private set; }
    /// <summary>
    /// 敌人卡组配置
    /// </summary>
    public int EnemyCardDeck { get; private set; }
    /// <summary>
    /// 敌人AI策略组
    /// </summary>
    public int EnemyAI { get; private set; }

    public const int __ID__ = 573091845;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BattleStagePath:" + BattleStagePath + ","
        + "BossId:" + BossId + ","
        + "EnemyCardDeck:" + EnemyCardDeck + ","
        + "EnemyAI:" + EnemyAI + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
