//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.level
{

public sealed partial class LevelsSaveItem :  Bright.Config.BeanBase 
{
    public LevelsSaveItem(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["LevelName"].IsString) { throw new SerializationException(); }  LevelName = _json["LevelName"]; }
        { if(!_json["LevelDesc"].IsString) { throw new SerializationException(); }  LevelDesc = _json["LevelDesc"]; }
        { if(!_json["Achievement"].IsNumber) { throw new SerializationException(); }  Achievement = _json["Achievement"]; }
        PostInit();
    }

    public LevelsSaveItem(int id, string LevelName, string LevelDesc, int Achievement ) 
    {
        this.Id = id;
        this.LevelName = LevelName;
        this.LevelDesc = LevelDesc;
        this.Achievement = Achievement;
        PostInit();
    }

    public static LevelsSaveItem DeserializeLevelsSaveItem(JSONNode _json)
    {
        return new level.LevelsSaveItem(_json);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 关卡名称
    /// </summary>
    public string LevelName { get; private set; }
    /// <summary>
    /// 关卡描述
    /// </summary>
    public string LevelDesc { get; private set; }
    /// <summary>
    /// 关卡成就：-1：未解锁；0：已解锁；&gt;1：得分
    /// </summary>
    public int Achievement { get; private set; }

    public const int __ID__ = 1029985417;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LevelName:" + LevelName + ","
        + "LevelDesc:" + LevelDesc + ","
        + "Achievement:" + Achievement + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
