//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.level
{

/// <summary>
/// 用于描述关卡/事件解锁条件
/// </summary>
public sealed partial class LevelUnlocker :  Bright.Config.BeanBase 
{
    public LevelUnlocker(JSONNode _json) 
    {
        { if(!_json["unlock_type"].IsNumber) { throw new SerializationException(); }  UnlockType = (level.UnlockType)_json["unlock_type"].AsInt; }
        { if(!_json["unlock_condition"].IsNumber) { throw new SerializationException(); }  UnlockCondition = _json["unlock_condition"]; }
        { if(!_json["extra_condition"].IsBoolean) { throw new SerializationException(); }  ExtraCondition = _json["extra_condition"]; }
        PostInit();
    }

    public LevelUnlocker(level.UnlockType unlock_type, int unlock_condition, bool extra_condition ) 
    {
        this.UnlockType = unlock_type;
        this.UnlockCondition = unlock_condition;
        this.ExtraCondition = extra_condition;
        PostInit();
    }

    public static LevelUnlocker DeserializeLevelUnlocker(JSONNode _json)
    {
        return new level.LevelUnlocker(_json);
    }

    /// <summary>
    /// 解锁类型(通关事件/关卡)
    /// </summary>
    public level.UnlockType UnlockType { get; private set; }
    /// <summary>
    /// 解锁条件(对应编号)
    /// </summary>
    public int UnlockCondition { get; private set; }
    /// <summary>
    /// 附加条件(*待增补)
    /// </summary>
    public bool ExtraCondition { get; private set; }

    public const int __ID__ = 1530525067;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "UnlockType:" + UnlockType + ","
        + "UnlockCondition:" + UnlockCondition + ","
        + "ExtraCondition:" + ExtraCondition + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
