//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.level
{

public sealed partial class LevelItem :  Bright.Config.BeanBase 
{
    public LevelItem(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["LevelName"].IsString) { throw new SerializationException(); }  LevelName = _json["LevelName"]; }
        { if(!_json["LevelDesc"].IsString) { throw new SerializationException(); }  LevelDesc = _json["LevelDesc"]; }
        { var _json1 = _json["LevelUnlockers"]; if(!_json1.IsArray) { throw new SerializationException(); } LevelUnlockers = new System.Collections.Generic.List<level.LevelUnlocker>(_json1.Count); foreach(JSONNode __e in _json1.Children) { level.LevelUnlocker __v;  { if(!__e.IsObject) { throw new SerializationException(); }  __v = level.LevelUnlocker.DeserializeLevelUnlocker(__e); }  LevelUnlockers.Add(__v); }   }
        { if(!_json["story1"].IsString) { throw new SerializationException(); }  Story1 = _json["story1"]; }
        { if(!_json["story2"].IsString) { throw new SerializationException(); }  Story2 = _json["story2"]; }
        { if(!_json["story3"].IsString) { throw new SerializationException(); }  Story3 = _json["story3"]; }
        { var _json1 = _json["Rewards"]; if(!_json1.IsArray) { throw new SerializationException(); } Rewards = new System.Collections.Generic.List<level.Reward>(_json1.Count); foreach(JSONNode __e in _json1.Children) { level.Reward __v;  { if(!__e.IsObject) { throw new SerializationException(); }  __v = level.Reward.DeserializeReward(__e); }  Rewards.Add(__v); }   }
        PostInit();
    }

    public LevelItem(int id, string LevelName, string LevelDesc, System.Collections.Generic.List<level.LevelUnlocker> LevelUnlockers, string story1, string story2, string story3, System.Collections.Generic.List<level.Reward> Rewards ) 
    {
        this.Id = id;
        this.LevelName = LevelName;
        this.LevelDesc = LevelDesc;
        this.LevelUnlockers = LevelUnlockers;
        this.Story1 = story1;
        this.Story2 = story2;
        this.Story3 = story3;
        this.Rewards = Rewards;
        PostInit();
    }

    public static LevelItem DeserializeLevelItem(JSONNode _json)
    {
        return new level.LevelItem(_json);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 关卡名称
    /// </summary>
    public string LevelName { get; private set; }
    /// <summary>
    /// 关卡描述
    /// </summary>
    public string LevelDesc { get; private set; }
    public System.Collections.Generic.List<level.LevelUnlocker> LevelUnlockers { get; private set; }
    /// <summary>
    /// 触发点1（战前）剧情
    /// </summary>
    public string Story1 { get; private set; }
    /// <summary>
    /// 触发点2（战胜）剧情
    /// </summary>
    public string Story2 { get; private set; }
    /// <summary>
    /// 触发点3（战败）剧情
    /// </summary>
    public string Story3 { get; private set; }
    public System.Collections.Generic.List<level.Reward> Rewards { get; private set; }

    public const int __ID__ = -923819347;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in LevelUnlockers) { _e?.Resolve(_tables); }
        foreach(var _e in Rewards) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in LevelUnlockers) { _e?.TranslateText(translator); }
        foreach(var _e in Rewards) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LevelName:" + LevelName + ","
        + "LevelDesc:" + LevelDesc + ","
        + "LevelUnlockers:" + Bright.Common.StringUtil.CollectionToString(LevelUnlockers) + ","
        + "Story1:" + Story1 + ","
        + "Story2:" + Story2 + ","
        + "Story3:" + Story3 + ","
        + "Rewards:" + Bright.Common.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
