//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.level
{

public sealed partial class LevelItems
{
    private readonly Dictionary<int, level.LevelItem> _dataMap;
    private readonly List<level.LevelItem> _dataList;
    
    public LevelItems(JSONNode _json)
    {
        _dataMap = new Dictionary<int, level.LevelItem>();
        _dataList = new List<level.LevelItem>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = level.LevelItem.DeserializeLevelItem(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, level.LevelItem> DataMap => _dataMap;
    public List<level.LevelItem> DataList => _dataList;

    public level.LevelItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public level.LevelItem Get(int key) => _dataMap[key];
    public level.LevelItem this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}