//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.level
{
    /// <summary>
    /// 标记关卡解锁条件
    /// </summary>
    public enum UnlockType
    {
        /// <summary>
        /// 完成关卡
        /// </summary>
        Level = 0,
        /// <summary>
        /// 完成事件
        /// </summary>
        Event = 1,
        /// <summary>
        /// 拥有物品
        /// </summary>
        Goods = 2,
    }
}
