//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;

namespace cfg
{
   
public sealed partial class Tables
{
    public card.CardItems CardItems {get; }
    public card.SpellItems SpellItems {get; }
    public skill.SkillItems SkillItems {get; }
    public buff.BaseBuffItems BaseBuffItems {get; }
    public buff.BuffItems BuffItems {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        CardItems = new card.CardItems(loader("card_carditems")); 
        tables.Add("card.CardItems", CardItems);
        SpellItems = new card.SpellItems(loader("card_spellitems")); 
        tables.Add("card.SpellItems", SpellItems);
        SkillItems = new skill.SkillItems(loader("skill_skillitems")); 
        tables.Add("skill.SkillItems", SkillItems);
        BaseBuffItems = new buff.BaseBuffItems(loader("buff_basebuffitems")); 
        tables.Add("buff.BaseBuffItems", BaseBuffItems);
        BuffItems = new buff.BuffItems(loader("buff_buffitems")); 
        tables.Add("buff.BuffItems", BuffItems);
        PostInit();

        CardItems.Resolve(tables); 
        SpellItems.Resolve(tables); 
        SkillItems.Resolve(tables); 
        BaseBuffItems.Resolve(tables); 
        BuffItems.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        CardItems.TranslateText(translator); 
        SpellItems.TranslateText(translator); 
        SkillItems.TranslateText(translator); 
        BaseBuffItems.TranslateText(translator); 
        BuffItems.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
