//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;

namespace cfg
{
   
public sealed partial class Tables
{
    public card.CardItems CardItems {get; }
    public card.SpellItems SpellItems {get; }
    public skill.SkillItems SkillItems {get; }
    public buff.BaseBuffItems BaseBuffItems {get; }
    public buff.BuffItems BuffItems {get; }
    public level.EventItems EventItems {get; }
    public level.EventDialogItems EventDialogItems {get; }
    public level.LevelItems LevelItems {get; }
    public level.LevelBattleItems LevelBattleItems {get; }
    public level.CardLibraries CardLibraries {get; }
    public level.LevelsSave LevelsSave {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        CardItems = new card.CardItems(loader("card_carditems")); 
        tables.Add("card.CardItems", CardItems);
        SpellItems = new card.SpellItems(loader("card_spellitems")); 
        tables.Add("card.SpellItems", SpellItems);
        SkillItems = new skill.SkillItems(loader("skill_skillitems")); 
        tables.Add("skill.SkillItems", SkillItems);
        BaseBuffItems = new buff.BaseBuffItems(loader("buff_basebuffitems")); 
        tables.Add("buff.BaseBuffItems", BaseBuffItems);
        BuffItems = new buff.BuffItems(loader("buff_buffitems")); 
        tables.Add("buff.BuffItems", BuffItems);
        EventItems = new level.EventItems(loader("level_eventitems")); 
        tables.Add("level.EventItems", EventItems);
        EventDialogItems = new level.EventDialogItems(loader("level_eventdialogitems")); 
        tables.Add("level.EventDialogItems", EventDialogItems);
        LevelItems = new level.LevelItems(loader("level_levelitems")); 
        tables.Add("level.LevelItems", LevelItems);
        LevelBattleItems = new level.LevelBattleItems(loader("level_levelbattleitems")); 
        tables.Add("level.LevelBattleItems", LevelBattleItems);
        CardLibraries = new level.CardLibraries(loader("level_cardlibraries")); 
        tables.Add("level.CardLibraries", CardLibraries);
        LevelsSave = new level.LevelsSave(loader("level_levelssave")); 
        tables.Add("level.LevelsSave", LevelsSave);
        PostInit();

        CardItems.Resolve(tables); 
        SpellItems.Resolve(tables); 
        SkillItems.Resolve(tables); 
        BaseBuffItems.Resolve(tables); 
        BuffItems.Resolve(tables); 
        EventItems.Resolve(tables); 
        EventDialogItems.Resolve(tables); 
        LevelItems.Resolve(tables); 
        LevelBattleItems.Resolve(tables); 
        CardLibraries.Resolve(tables); 
        LevelsSave.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        CardItems.TranslateText(translator); 
        SpellItems.TranslateText(translator); 
        SkillItems.TranslateText(translator); 
        BaseBuffItems.TranslateText(translator); 
        BuffItems.TranslateText(translator); 
        EventItems.TranslateText(translator); 
        EventDialogItems.TranslateText(translator); 
        LevelItems.TranslateText(translator); 
        LevelBattleItems.TranslateText(translator); 
        CardLibraries.TranslateText(translator); 
        LevelsSave.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
